### ISSUE TITLE
怎么绑定七牛服务器去上传图片？

### ISSUE THREAD

**Issue by yuiooo** [liuhong1happy/react-umeditor#1]
我现在的需求是在编辑器里能上传图片，现在看react-umeditor的介绍里是使用plugins来告诉编辑器uploader，我现在用的是七牛服务器的上传服务，它需要一个上传token，我该在哪里传递这个参数？
还有就是在哪里处理上传完成的回调？

**Comment by liuhong1happy** [comment]
你好！介于目前编辑器无法支持七牛上传。在0.2.27版本中加入`customUploader`属性，请自行实现`src/utils/FileUpload`中的所有对外公开方法。
我们会尽快在下一版本中加入原生对七牛上传的支持。谢谢你的反馈～

**Comment by yuiooo** [comment]
请问有没有关于customUploader的使用的demo参考下呢

**Comment by liuhong1happy** [comment]
@yuiooo 请参考七牛的关于“[上传](http://developer.qiniu.com/code/v6/sdk/javascript.html#upload)”的文档。

**Comment by yuiooo** [comment]
```javascript
const plugins = {
			image: {
				uploader:{
					url:'http://upload.qiniu.com',
					name:'qiniu'
				},
				customUploader:umeditorQiniuUploader
			}
		}
...
// render()
    <Editor ref="editor" defaultValue=" " plugins={plugins}></Editor>
```
上面是我的代码，运行结果上传的url是'http://upload.qiniu.com'，umeditorQiniuUploader是我按照你们的src/utils/FileUpload.js格式写的一个上传器，但是无论我怎么传这个customUploader，无论uploader是否传值，实际代码运行的还是自带的uploader，例如
```javascript
const plugins = {
			image: {
				customUploader:umeditorQiniuUploader
			}
		}
```
这样，实际上传的url就是'/upload'，就是说，customUploader并没有运行，这是为什么呢

**Comment by liuhong1happy** [comment]
@yuiooo 欢迎加我qq284362096（刘红）！能详细给定你的umeditorQiniuUploader具体实现嘛。尽快给你相应的正确代码方案。
