### ISSUE TITLE
在其他页面触发了setState操作

### ISSUE THREAD

**Issue by grunmin** [liuhong1happy/react-umeditor#24]
我尝试将编辑器用在[这个项目](https://github.com/zuiidea/antd-admin)上, 编辑器可以正常加载. 但是加载了编辑器页面后切换到其他页面, 点击鼠标会报warning. 初学react, 不是很懂如何解决

![image](https://cloud.githubusercontent.com/assets/4323398/21168790/d3d024e6-c1f1-11e6-9317-27eb17a7cf76.png)

警告信息是
```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the EditorCore component.
```

最后两行是
```
handleRangeChange   @   EditorCore.react.js:226
handleMouseUp   @   EditorContentEditableDiv.react.js:109
```

完整的是
![image](https://cloud.githubusercontent.com/assets/4323398/21168895/895f9044-c1f2-11e6-9b46-3552638df2c9.png)

**Comment by liuhong1happy** [comment]
@grunmin 这里却是是一个bug存在，会在后续版本中修复。

**Comment by grunmin** [comment]
有可能是使用dva的原因, 编辑器组件应该不适合用stateless

**Comment by dlyt** [comment]
我也遇到这个问题了，不知道修复好了没有。

**Comment by grunmin** [comment]
@dlyt 看commit应该是没有

**Comment by elevensky** [comment]
我也遇到了

**Comment by dlyt** [comment]
找到EditorContentEditableDiv.react.js,替换componentDidMount用下面的代码。
```js
{
		key: 'componentDidMount',
		value: function componentDidMount(e) {
			this.handleWindowMouseDown = this.handleWindowMouseDown.bind(this)
			this.handleMouseUp = this.handleMouseUp.bind(this)
			window.addEventListener("mousedown", this.handleWindowMouseDown);
			window.addEventListener("mouseup", this.handleMouseUp);
		}
}
```

**Comment by liuhong1happy** [comment]
已经修改，请使用最新版本1.0
