### ISSUE TITLE
ImageDialog.react.js 中的 onSuccess 不支持自定义配置吗？

### ISSUE THREAD

**Issue by raisezhang** [liuhong1happy/react-umeditor#26]
你好，接口上传图片的判断条件貌似太过写死...
能不能自定义实现 onSuccess 接口返回 images ？

**Comment by liuhong1happy** [comment]
可以考虑加上这样的接口。

**Comment by raisezhang** [comment]
恩  多谢啦   或者可以直接把   uploader 里面需要的 config 透传过去， 实现 onEnd 方法来修改

**Comment by liuhong1happy** [comment]
1.0版本目前支持自定义功能按钮，修改了图片上传逻辑。

**Comment by raisezhang** [comment]
Thanks ~
