### ISSUE TITLE
图片上传绝对是个坑。

### ISSUE THREAD

**Issue by weishijun14** [liuhong1happy/react-umeditor#34]
{'data': {'image_src': xxx} , status:'success'}，这是上传自己服务器的返回数据格式。

开发者并没有提到。加群也没人理我。

是我自己google出来的。

绝对是个坑，警示后人！

**Comment by mumukun** [comment]
点个赞，我也是看了源码才知道。

**Comment by Jaction** [comment]
怎么修改umeditor上传的图片的url和出入参数？有没有相关的api？

能不能告诉我一声，我找不到图片上传api

**Comment by liuhong1happy** [comment]
1.0版本已经更新图片上传逻辑
