### ISSUE TITLE
this.argumentUploder is not a function

### ISSUE THREAD

**Issue by lany9527** [liuhong1happy/react-umeditor#42]
点击上传图片报错  this.argumentUploder is not a function，求解

**Comment by greyj2009** [comment]
我也是这个问题，我用的自定义上传方式

**Comment by libra-eric** [comment]
https://github.com/liuhong1happy/react-umeditor/blob/master/lib/components/plugins/ImageUpload.react.js#L140,这里有个拼写错误

**Comment by liuhong1happy** [comment]
@lany9527 @libra-eric 感谢
