### ISSUE TITLE
希望可以将toolbar 做得灵活一些，让用户可以自己加按钮写功能

### ISSUE THREAD

**Issue by quxq** [liuhong1happy/react-umeditor#47]
目前看到的写得比较死板，不能扩展工具条的功能

**Comment by HarryChen0506** [comment]
umeditor其实不怎么好，源码没有百度专业的编辑器好，包括添加字体大小都不行。所有还是让作者封个专业版的百度编辑器把 @liuhong1happy

**Comment by liuhong1happy** [comment]
@HarryChen0506 核心代码逻辑，在https://github.com/liuhong1happy/react-umeditor/blob/master/src/components/core/EditorCore.react.js 文件中，欢迎提交未实现的组件。

**Comment by liuhong1happy** [comment]
新增插件的文档，以前有写，欢迎作为参考。
https://github.com/liuhong1happy/react-umeditor/blob/86923b88cad525cb647870bffa712dcbe94fe40c/docs/contribute_cn.md

**Comment by liuhong1happy** [comment]
1.0版本允许自定义功能按钮。欢迎贡献新的功能按钮。
