### ISSUE TITLE
路由改变永远显示 正在加载...

### ISSUE THREAD

**Issue by 531614842fangwei** [liuhong1happy/react-umeditor#48]
![image](https://user-images.githubusercontent.com/12245343/34760071-3b6bd544-f619-11e7-981f-cd1e6f190f94.png)
![image](https://user-images.githubusercontent.com/12245343/34760109-65f9f016-f619-11e7-86cc-1d597b69a024.png)
对比npm上的编译后代码和github项目源码，发现这两处写法有差异，导致onEditorMount未被触发，EditorEventEmitter中的this.isStart第一次赋值后永远为true,所以路由更改后页面一直显示  正在加载...

**Comment by 531614842fangwei** [comment]
查看代码历史发现这应该是一个笔误，但是好像修改后没有打到包里

**Comment by liuhong1happy** [comment]
已经修改，谢谢反馈。 @531614842fangwei
