### ISSUE TITLE
开发环境和服务器生产环境，怎么标签表情都没了

### ISSUE THREAD

**Issue by Jaction** [liuhong1happy/react-umeditor#57]
```
// 项目打包构建发到服务器
npm run build
// 构建react-umeditor居然没有了
```

## 这是阿里云生产环境
![image](https://user-images.githubusercontent.com/17811893/40871269-2d145882-666b-11e8-9c53-840fb8b41624.png)

**Comment by Jaction** [comment]
是图片路径导致的

**Comment by jszcl** [comment]
怎么改的？我也是antd里碰到这个情况
