### ISSUE TITLE
图片限制大小和后台返回的错误的处理!

### ISSUE THREAD

**Issue by helpceo** [liuhong1happy/react-umeditor#63]
上传图片的时候,没有找到哪地方能限制图片大小的属性,如果上传的图片过大,后台就会返回错误,前面也没有找到捕获错误的地方!
建议:添加图片上传的时候提供一个字段来限制图片的大小,图片超出范围就直接不发送http的请求,或者提示一下也可以.

**Comment by liuhong1happy** [comment]
请自定义customUploader
