### ISSUE TITLE
如何获取纯文本

### ISSUE THREAD

**Issue by xuguanqun** [liuhong1happy/react-umeditor#88]
只能返回dom字符串，尝试调用原生百度编辑器支持的的getContentTxt方法失败

**Comment by liuhong1happy** [comment]
你好，这是用react重写的编辑器，借用了百度的编辑器UI，谢谢！

**Comment by xuguanqun** [comment]
那如何获取纯文本呢

**Comment by liuhong1happy** [comment]
通过findDOMNode方法获取到dom节点，自行取相应文本内容。谢谢
