### ISSUE TITLE
在react项目中的使用问题

### ISSUE THREAD

**Issue by yuweilan** [liuhong1happy/react-umeditor#9]
在项目中引入使用的的时候，npm install react-umeditor --save安装以后

`    <link rel="stylesheet" href="../../dist/third-part/mathquill/mathquill.css"/>
    <link rel="stylesheet" href="../../dist/react-umeditor.css" type="text/css" />`
`<script src="../../dist/third-part/jquery.min.js"></script>
    <script src="../../dist/third-part/mathquill/mathquill.js"></script>`

这些都必须要重新引入一下么？
能集成在react-umeditor中么？

**Comment by liuhong1happy** [comment]
mathquill代码还再继续改版中，等它稳定后，有考虑继承到编辑器中。谢谢你的反馈～
如果，你没有考虑使用数学公式的功能，可以不用引用mathquill的css和js。
